chore: added github workflows

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -4,10 +4,45 @@ on:
   push:
     branches:
       - dev
+  pull_request:
+    branches:
+      - dev
 
 jobs:
-  build:
+  build_and_test:
     runs-on: ubuntu-latest
+    env:
+      TEST_USERNAME: postgres
+      TEST_PASSWORD: password
+      TEST_DB_NAME: db_name
+      TEST_DB_HOST: localhost
+      TEST_DB_PORT: 5432
+      TEST_DB_CONNECTION: pgsql
+      TEST_TIMEZONE: Africa/Lagos
+      TEST_SSLMODE: disable
+      TEST_MIGRATE: true
+      REDIS_PORT: 6379
+      REDIS_HOST: localhost
+      REDIS_DB: 0
+
+    services:
+      postgres:
+        image: postgres:latest
+        env:
+          POSTGRES_USER: ${{ env.TEST_USERNAME }}
+          POSTGRES_PASSWORD: ${{ env.TEST_PASSWORD }}
+          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
+        ports:
+          - 5432:5432
+      redis:
+        image: redis
+        options: >-
+          --health-cmd "redis-cli ping"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+        ports:
+          - 6379:6379
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -15,32 +50,12 @@ jobs:
         uses: actions/setup-go@v4
         with:
           go-version: "1.22.1"
-      - name: Build the application
-        run: go build -o learnai_dev
-
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    env:
-      POSTGRES_USER: postgres
-      POSTGRES_PASSWORD: password
-      POSTGRES_DB: db_name
-    services:
-      postgres:
-        image: postgres:latest
-        env:
-          POSTGRES_USER: ${{ env.POSTGRES_USER }}
-          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
-          POSTGRES_DB: ${{ env.POSTGRES_DB }}
-        ports:
-          - 5432:5432
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
-      - name: Create the app config file
+      - name: Create app config file
         run: cp app-sample.env app.env
-      - name: Run The Project
-        run: nohup go run main.go > /dev/null 2>&1 &
+      - name: Build the application
+        run: go build -o development_app
+      - name: Run the application
+        run: nohup ./development_app > /dev/null 2>&1 &
       - name: Wait for application to start
         run: sleep 30s
       - name: Test for reachability
@@ -50,13 +65,30 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-    needs: test
+    needs: build_and_test
+    if: github.event_name == 'push'
     env:
       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
       SSH_HOST: ${{ secrets.SSH_HOST }}
       SSH_PORT: ${{ secrets.SSH_PORT }}
       SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
-      PROCESS_NAME: run_learnai_dev
+      SERVER_PORT: "7000"
+      DB_NAME: "development_db"
+      USERNAME: "development_user"
+      APP_NAME: "development"
+      APP_URL: "https://deployment.api-golang.boilerplate.hng.tech"
+      REDIS_PORT: "6130"
+      REDIS_HOST: "0.0.0.0"
+      REDIS_DB: "0"
+      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
+      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
+      FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
+      FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
+      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
+      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
+      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
+      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
+      MAIL_PORT: ${{ secrets.MAIL_PORT }}
 
     steps:
       - name: SSH into server and deploy
@@ -68,29 +100,34 @@ jobs:
           port: ${{ env.SSH_PORT }}
           script: |
             export APPROOT=~/deployments/development
-            export PATH=$PATH:~/.nvm/versions/node/v20.15.1/bin
-            export PATH=$PATH:/usr/local/go/bin
-
             mkdir -p $APPROOT
             cd $APPROOT
 
             if [ -d "$APPROOT/.git" ]; then
-                # Navigate to the repository directory and pull changes
-                cd $APPROOT || { echo "Failed to navigate to web root directory"; exit 1; }
-                git reset --hard HEAD || { echo "Failed to reset local changes"; exit 1; }
-                git pull origin main || { echo "Failed to pull latest changes"; exit 1; }
+              # Navigate to the repository directory and pull changes
+              cd $APPROOT || { echo "Failed to navigate to web root directory"; exit 1; }
+              git reset --hard HEAD || { echo "Failed to reset local changes"; exit 1; }
+              git pull origin dev || { echo "Failed to pull latest changes"; exit 1; }
             else
-                git clone -b dev http://github.com/${{ github.repository }} . || { echo "Failed to clone repository"; exit 1; }
+              git clone -b dev https://github.com/${{ github.repository}} . || { echo "Failed to clone repository"; exit 1; }
             fi
 
-            cp app-sample.env app.env
-            go build -o ~/deployments/development/learnai_dev
-
-            # Check if pm2 is already running
-            if pm2 list | grep -q "${{ env.PROCESS_NAME }}"; then
-              echo "Process ${{ env.PROCESS_NAME }} is running. Restarting..."
-              pm2 restart "${{ env.PROCESS_NAME }}"
-            else
-              echo "Process ${{ env.PROCESS_NAME }} is not running. Starting..."
-              pm2 start "${{ env.PROCESS_NAME }}".sh
-            fi
+            bash ./scripts/deploy_app.sh development https://github.com/${{ github.repository}} \
+              SERVER_PORT=${{ env.SERVER_PORT }} \
+              DB_NAME=${{ env.DB_NAME }} \
+              USERNAME=${{ env.USERNAME }} \
+              APP_NAME=${{ env.APP_NAME }} \
+              APP_URL=${{ env.APP_URL }} \
+              REDIS_PORT=${{ env.REDIS_PORT }} \
+              REDIS_HOST=${{ env.REDIS_HOST }} \
+              REDIS_DB=${{ env.REDIS_DB }} \
+              GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} \
+              GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }} \
+              FACEBOOK_CLIENT_ID=${{ env.FACEBOOK_CLIENT_ID }} \
+              FACEBOOK_CLIENT_SECRET=${{ env.FACEBOOK_CLIENT_SECRET }} \
+              SESSION_SECRET=${{ env.SESSION_SECRET }} \
+              MAIL_SERVER=${{ env.MAIL_SERVER }} \
+              MAIL_USERNAME=${{ env.MAIL_USERNAME }} \
+              MAIL_PASSWORD=${{ env.MAIL_PASSWORD }} \
+              MAIL_PORT=${{ env.MAIL_PORT }} \
+              MIGRATE=true
diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -1,12 +1,12 @@
-name: Build, Test, and Deploy for Production
+name: Build, Test, and Deploy for Staging
 
 on:
   push:
     branches:
-      - main
+      - staging
   pull_request:
     branches:
-      - main
+      - staging
 
 jobs:
   build_and_test:
@@ -49,9 +49,9 @@ jobs:
       - name: Create app config file
         run: cp app-sample.env app.env
       - name: Build the application
-        run: go build -o production_app
+        run: go build -o staging_app
       - name: Run the application
-        run: nohup ./production_app > /dev/null 2>&1 &
+        run: nohup ./staging_app > /dev/null 2>&1 &
       - name: Wait for application to start
         run: sleep 30s
       - name: Test for reachability
@@ -68,12 +68,12 @@ jobs:
       SSH_HOST: ${{ secrets.SSH_HOST }}
       SSH_PORT: ${{ secrets.SSH_PORT }}
       SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
-      SERVER_PORT: 9000
-      DB_NAME: "production_db"
-      USERNAME: "production_user"
-      APP_NAME: "production"
-      APP_URL: "https://api-golang.boilerplate.hng.tech"
-      REDIS_PORT: 6132
+      SERVER_PORT: 8000
+      DB_NAME: "staging_db"
+      USERNAME: "staging_user"
+      APP_NAME: "staging"
+      APP_URL: "https://staging.api-golang.boilerplate.hng.tech"
+      REDIS_PORT: 6131
       REDIS_HOST: "0.0.0.0"
       REDIS_DB: 0
       GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
@@ -85,6 +85,7 @@ jobs:
       MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
       MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
       MAIL_PORT: ${{ secrets.MAIL_PORT }}
+
     steps:
       - name: SSH into server and deploy
         uses: appleboy/ssh-action@v1.0.3
@@ -94,7 +95,7 @@ jobs:
           password: ${{ env.SSH_PASSWORD }}
           port: ${{ env.SSH_PORT }}
           script: |
-            export APPROOT=~/deployments/production
+            export APPROOT=~/deployments/staging
             mkdir -p $APPROOT
             cd $APPROOT
 
@@ -102,12 +103,12 @@ jobs:
               # Navigate to the repository directory and pull changes
               cd $APPROOT || { echo "Failed to navigate to web root directory"; exit 1; }
               git reset --hard HEAD || { echo "Failed to reset local changes"; exit 1; }
-              git pull origin main || { echo "Failed to pull latest changes"; exit 1; }
+              git pull origin staging || { echo "Failed to pull latest changes"; exit 1; }
             else
-              git clone -b main https://github.com/${{ github.repository}} . || { echo "Failed to clone repository"; exit 1; }
+              git clone -b staging https://github.com/${{ github.repository}} . || { echo "Failed to clone repository"; exit 1; }
             fi
 
-            bash ./scripts/deploy_app.sh production https://github.com/${{ github.repository}} 
+            bash ./scripts/deploy_app.sh staging https://github.com/${{ github.repository}}
               SERVER_PORT=${{ env.SERVER_PORT }} \
               DB_NAME=${{ env.DB_NAME }} \
               USERNAME=${{ env.USERNAME }} \
